name: GitHub Metrics
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: TU_USUARIO
          config_timezone: Europe/Madrid
          base: header, activity, community, repositories, metadata
          template: classic
          plugins_isocalendar: yes
          plugins_isocalendar_duration: full-year
          plugins_languages: yes
          plugins_languages_colors: github
          plugins_languages_limit: 8
          plugins_languages_sections: most-used
          plugins_languages_details: percentage
          plugins_languages_threshold: 1%
          plugins_habits: yes
          plugins_habits_facts: yes
          plugins_habits_charts: yes
          plugins_activity: yes
          plugins_activity_limit: 5
          plugins_activity_load: 200
          plugins_activity_days: 30
          plugins_lines: yes
          plugins_followup: yes
          plugins_followup_sections: repositories
          config_display: columns
